#!/usr/bin/env bash

changedFiles=$(git status --porcelain --no-renames)

format_dart_files() {
  echo "Running flutter format"
  make format-check
}

containsDartFiles=false
formatDartExitCode=0

while read gitFileStatus changedFile; do
  # skip deleted files
  if [ "$gitFileStatus" == 'D' ]; then continue; fi

  if [[ "$changedFile" =~ ".dart" ]]; then
    containsDartFiles=true
    break
  fi
done <<<"$changedFiles"

if [ $containsDartFiles == true ] ; then
    format_dart_files
    formatDartExitCode=$?
fi

if [[ $formatDartExitCode -ne 0 ]] ; then
  echo
  echo "Pre-commit failed"
  exit 1
fi
exit 0