version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:30"
      timezone: Europe/Paris
      open-pull-requests-limit: 1
