include: package:flutter_lints/flutter.yaml

linter:
  # Switch on or off rules
  rules:
    always_use_package_imports: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    avoid_print: true
    constant_identifier_names: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    use_key_in_widget_constructors: false
    depend_on_referenced_packages: false
    require_trailing_commas: true

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  # Adjust severity of defined rules
  errors:
    missing_return: error
    dead_code: error
    unused_element: error
    always_use_package_imports: error
    deprecated_member_use: ignore #TODO: remove this once WillPopScope has been fixed !!
