import 'package:equatable/equatable.dart';

class Department extends Equatable {
  final String code;
  final String name;
  final String displayedName;

  Department({required this.code, required this.name, required this.displayedName});

  @override
  List<Object> get props => [code, name, displayedName];
}

class DepartmentHelper {
  static List<Department> getDepartment() {
    return [
      Department(code: "01", name: "Ain", displayedName: "01 - Ain"),
      Department(code: "02", name: "Aisne", displayedName: "02 - Aisne"),
      Department(code: "03", name: "Allier", displayedName: "03 - Allier"),
      Department(code: "04", name: "Alpes-de-Haute-Provence", displayedName: "04 - Alpes-de-Haute-Provence"),
      Department(code: "05", name: "Hautes-Alpes", displayedName: "05 - Hautes-Alpes"),
      Department(code: "06", name: "Alpes-Maritimes", displayedName: "06 - Alpes-Maritimes"),
      Department(code: "07", name: "Ardèche", displayedName: "07 - Ardèche"),
      Department(code: "08", name: "Ardennes", displayedName: "08 - Ardennes"),
      Department(code: "09", name: "Ariège", displayedName: "09 - Ariège"),
      Department(code: "10", name: "Aube", displayedName: "10 - Aube"),
      Department(code: "11", name: "Aude", displayedName: "11 - Aude"),
      Department(code: "12", name: "Aveyron", displayedName: "12 - Aveyron"),
      Department(code: "13", name: "Bouches-du-Rhône", displayedName: "13 - Bouches-du-Rhône"),
      Department(code: "14", name: "Calvados", displayedName: "14 - Calvados"),
      Department(code: "15", name: "Cantal", displayedName: "15 - Cantal"),
      Department(code: "16", name: "Charente", displayedName: "16 - Charente"),
      Department(code: "17", name: "Charente-Maritime", displayedName: "17 - Charente-Maritime"),
      Department(code: "18", name: "Cher", displayedName: "18 - Cher"),
      Department(code: "19", name: "Corrèze", displayedName: "19 - Corrèze"),
      Department(code: "2A", name: "Corse-du-Sud", displayedName: "2A - Corse-du-Sud"),
      Department(code: "2B", name: "Haute-Corse", displayedName: "2B - Haute-Corse"),
      Department(code: "21", name: "Côte-d'Or", displayedName: "21 - Côte-d'Or"),
      Department(code: "22", name: "Côtes-d'Armor", displayedName: "22 - Côtes-d'Armor"),
      Department(code: "23", name: "Creuse", displayedName: "23 - Creuse"),
      Department(code: "24", name: "Dordogne", displayedName: "24 - Dordogne"),
      Department(code: "25", name: "Doubs", displayedName: "25 - Doubs"),
      Department(code: "26", name: "Drôme", displayedName: "26 - Drôme"),
      Department(code: "27", name: "Eure", displayedName: "27 - Eure"),
      Department(code: "28", name: "Eure-et-Loir", displayedName: "28 - Eure-et-Loir"),
      Department(code: "29", name: "Finistère", displayedName: "29 - Finistère"),
      Department(code: "30", name: "Gard", displayedName: "30 - Gard"),
      Department(code: "31", name: "Haute-Garonne", displayedName: "31 - Haute-Garonne"),
      Department(code: "32", name: "Gers", displayedName: "32 - Gers"),
      Department(code: "33", name: "Gironde", displayedName: "33 - Gironde"),
      Department(code: "34", name: "Hérault", displayedName: "34 - Hérault"),
      Department(code: "35", name: "Ille-et-Vilaine", displayedName: "35 - Ille-et-Vilaine"),
      Department(code: "36", name: "Indre", displayedName: "36 - Indre"),
      Department(code: "37", name: "Indre-et-Loire", displayedName: "37 - Indre-et-Loire"),
      Department(code: "38", name: "Isère", displayedName: "38 - Isère"),
      Department(code: "39", name: "Jura", displayedName: "39 - Jura"),
      Department(code: "40", name: "Landes", displayedName: "40 - Landes"),
      Department(code: "41", name: "Loir-et-Cher", displayedName: "41 - Loir-et-Cher"),
      Department(code: "42", name: "Loire", displayedName: "42 - Loire"),
      Department(code: "43", name: "Haute-Loire", displayedName: "43 - Haute-Loire"),
      Department(code: "44", name: "Loire-Atlantique", displayedName: "44 - Loire-Atlantique"),
      Department(code: "45", name: "Loiret", displayedName: "45 - Loiret"),
      Department(code: "46", name: "Lot", displayedName: "46 - Lot"),
      Department(code: "47", name: "Lot-et-Garonne", displayedName: "47 - Lot-et-Garonne"),
      Department(code: "48", name: "Lozère", displayedName: "48 - Lozère"),
      Department(code: "49", name: "Maine-et-Loire", displayedName: "49 - Maine-et-Loire"),
      Department(code: "50", name: "Manche", displayedName: "50 - Manche"),
      Department(code: "51", name: "Marne", displayedName: "51 - Marne"),
      Department(code: "52", name: "Haute-Marne", displayedName: "52 - Haute-Marne"),
      Department(code: "53", name: "Mayenne", displayedName: "53 - Mayenne"),
      Department(code: "54", name: "Meurthe-et-Moselle", displayedName: "54 - Meurthe-et-Moselle"),
      Department(code: "55", name: "Meuse", displayedName: "55 - Meuse"),
      Department(code: "56", name: "Morbihan", displayedName: "56 - Morbihan"),
      Department(code: "57", name: "Moselle", displayedName: "57 - Moselle"),
      Department(code: "58", name: "Nièvre", displayedName: "58 - Nièvre"),
      Department(code: "59", name: "Nord", displayedName: "59 - Nord"),
      Department(code: "60", name: "Oise", displayedName: "60 - Oise"),
      Department(code: "61", name: "Orne", displayedName: "61 - Orne"),
      Department(code: "62", name: "Pas-de-Calais", displayedName: "62 - Pas-de-Calais"),
      Department(code: "63", name: "Puy-de-Dôme", displayedName: "63 - Puy-de-Dôme"),
      Department(code: "64", name: "Pyrénées-Atlantiques", displayedName: "64 - Pyrénées-Atlantiques"),
      Department(code: "65", name: "Hautes-Pyrénées", displayedName: "65 - Hautes-Pyrénées"),
      Department(code: "66", name: "Pyrénées-Orientales", displayedName: "66 - Pyrénées-Orientales"),
      Department(code: "67", name: "Bas-Rhin", displayedName: "67 - Bas-Rhin"),
      Department(code: "68", name: "Haut-Rhin", displayedName: "68 - Haut-Rhin"),
      Department(code: "69", name: "Rhône", displayedName: "69 - Rhône"),
      Department(code: "70", name: "Haute-Saône", displayedName: "70 - Haute-Saône"),
      Department(code: "71", name: "Saône-et-Loire", displayedName: "71 - Saône-et-Loire"),
      Department(code: "72", name: "Sarthe", displayedName: "72 - Sarthe"),
      Department(code: "73", name: "Savoie", displayedName: "73 - Savoie"),
      Department(code: "74", name: "Haute-Savoie", displayedName: "74 - Haute-Savoie"),
      Department(code: "75", name: "Paris", displayedName: "75 - Paris"),
      Department(code: "76", name: "Seine-Maritime", displayedName: "76 - Seine-Maritime"),
      Department(code: "77", name: "Seine-et-Marne", displayedName: "77 - Seine-et-Marne"),
      Department(code: "78", name: "Yvelines", displayedName: "78 - Yvelines"),
      Department(code: "79", name: "Deux-Sèvres", displayedName: "79 - Deux-Sèvres"),
      Department(code: "80", name: "Somme", displayedName: "80 - Somme"),
      Department(code: "81", name: "Tarn", displayedName: "81 - Tarn"),
      Department(code: "82", name: "Tarn-et-Garonne", displayedName: "82 - Tarn-et-Garonne"),
      Department(code: "83", name: "Var", displayedName: "83 - Var"),
      Department(code: "84", name: "Vaucluse", displayedName: "84 - Vaucluse"),
      Department(code: "85", name: "Vendée", displayedName: "85 - Vendée"),
      Department(code: "86", name: "Vienne", displayedName: "86 - Vienne"),
      Department(code: "87", name: "Haute-Vienne", displayedName: "87 - Haute-Vienne"),
      Department(code: "88", name: "Vosges", displayedName: "88 - Vosges"),
      Department(code: "89", name: "Yonne", displayedName: "89 - Yonne"),
      Department(code: "90", name: "Territoire de Belfort", displayedName: "90 - Territoire de Belfort"),
      Department(code: "91", name: "Essonne", displayedName: "91 - Essonne"),
      Department(code: "92", name: "Hauts-de-Seine", displayedName: "92 - Hauts-de-Seine"),
      Department(code: "93", name: "Seine-Saint-Denis", displayedName: "93 - Seine-Saint-Denis"),
      Department(code: "94", name: "Val-de-Marne", displayedName: "94 - Val-de-Marne"),
      Department(code: "95", name: "Val-d'Oise", displayedName: "95 - Val-d'Oise"),
      Department(code: "971", name: "Guadeloupe", displayedName: "971 - Guadeloupe"),
      Department(code: "972", name: "Martinique", displayedName: "972 - Martinique"),
      Department(code: "973", name: "Guyane", displayedName: "973 - Guyane"),
      Department(code: "974", name: "La Réunion", displayedName: "974 - La Réunion"),
      Department(code: "976", name: "Mayotte", displayedName: "976 - Mayotte"),
      Department(code: "Etranger", name: "Hors de France", displayedName: "Etranger - Hors de France"),
    ];
  }
}
